import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "eCommerce Sample",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="text-base text-black max-w-screen">
      <body className={`${montserrat.className} w-full`}>
        <div className="ad-bar w-full bg-[#E6E6E6] p-4 py-1 flex items-center">
          <p className="text-sm" >Returns are free within 14 days</p>
        </div>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
